### ISSUE TITLE
Calendar web display

### ISSUE THREAD

**Issue by brianblain** [brianblain/TBS#2]
weird characters (">)when event is tagged as a livestream:

instead of: View Event Website">Live Streamed

use: Livestream Link

September 2 @ 7:00 pm - 9:00 pm	
Johnny Max Band

View Event Website">Live Streamed
Fonthill Bandshell 20 Peltham, Fonthill

Register at www.fonthill.com

**Comment by rdbrinkhurst** [comment]
I see you mean the "list" display - this page http://tbs.366technology.com/events/list/

**Comment by brianblain** [comment]
yes, these two stray characters: ">

**Comment by rdbrinkhurst** [comment]
I've fixed issue #2  - please have a look.

**Comment by brianblain** [comment]
I selected a random event and added livestream and this is how it displays (list):
![Screen Shot 2021-09-03 at 3 07 50 PM](https://user-images.githubusercontent.com/11864078/132055116-1e60fd48-0d01-4f91-ae82-4d14735cbed3.png)

Can we change the text from View Event Website to "Livestream Link"  and make it the same font & size as the venue & date  (maybe underline...)

**Comment by rdbrinkhurst** [comment]
Yes - it's done.
