### ISSUE TITLE
Calendar Web Navigation

### ISSUE THREAD

**Issue by brianblain** [brianblain/TBS#3]
Some links need to be changed and updated - and verified

the URL torontobluessociety.com/live-blues  must point to calendar <http://tbs.366technology.com/events/>

the URL torontobluessociety.com/new/live-blues  must point to calendar <http://tbs.366technology.com/events/>

the buttons and menu items called "Live Blues" must point to calendar <http://tbs.366technology.com/events/>

the buttons and menu items called "TBS Events" must point to <http://tbs.366technology.com/category/events/>  (which is a different page with just a few TBS Events)

need to avoid any confusion between these pages

**Comment by rdbrinkhurst** [comment]
http://tbs.366technology.com/live-blues and http://tbs.366technology.com/new/live-blues now forward to http://tbs.366technology.com/events/

All of the buttons I'm seeing on the test already go to the right place. Are you seeing buttons that go to the wrong place?
