### ISSUE TITLE
Search Function only finds results in the currently displayed month

### ISSUE THREAD

**Issue by brianblain** [brianblain/TBS#6]
apparently this is not fixable so we can live with it

**Comment by rdbrinkhurst** [comment]
I see no case of this. In every instance, I'm able to search across months.

**Comment by brianblain** [comment]
If you've got the September (month view) up and search for Bisson (Oct 23 gig), it will say no results.  If you have Oct monthly view, it will find him.  In list view, no problem.  I think maybe Dean consulted the calendar developer about this

**Comment by rdbrinkhurst** [comment]
OK - I'll consider this issue closed. I think it would be worse to jump a user ahead a month (or even a few months - depending on the artist) when they didn't ask to be there. It would seem like software bug, and they might not even know that got sent to another month.

**Comment by brianblain** [comment]
But picture when a user opens the calendar on sept 30 and he’s heard that jack de Keyzer is playing next week so he searches and finds no results. Just sayin…

**Comment by rdbrinkhurst** [comment]
I definitely understand your point, but I think the solution would be worse than the problem, and it's also not possible anyway. I think the text that is displayed covers the issue as well.

**Comment by brianblain** [comment]
gotcha
