### ISSUE TITLE
Newsletter Export RTF - clean up stray commas

### ISSUE THREAD

**Issue by brianblain** [brianblain/TBS#8]

**Comment by rdbrinkhurst** [comment]
OK - this is done - please have a look

**Comment by brianblain** [comment]
oops I found a stray (after 30 North) 

Saturday, September 25

Serena Ryder 2:00 pm to 4:00 pm, Westben Willow Hill, 6698 County Road 30 North,, Campbellford, 1-705-653-5508, Toronto-based vocal powerhouse Serena Ryder is a platinum-selling artist adored by fans, peers and critics alike, in part due to her raw and earnest songwriting, and beautifully electric live performances. second show September 

looked at the edit page but couldn't see what might have caused it

**Comment by rdbrinkhurst** [comment]
It's an entry error - see http://tbs.366technology.com/new/wp-admin/post.php?post=18969&action=edit - someone put a comma after North that shouldn't be there. It needs to be removed from the data.

**Comment by brianblain** [comment]
Ironic - that's the only entry Derek made...
